// This file is "main.dart"
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'UserStats.freezed.dart';
part 'UserStats.g.dart';

@freezed
class UserStats with _$UserStats {
  const factory UserStats({
    required String id,
    required String uid,
    required String name,
    required String description,
    required String image,
  }) = _UserStats;

  factory UserStats.fromJson(Map<String, Object?> json) =>
      _$UserStatsFromJson(json);
}

class TimestampSerializer implements JsonConverter<DateTime, dynamic> {
  const TimestampSerializer();

  @override
  DateTime fromJson(dynamic timestamp) => timestamp.toDate();

  @override
  Timestamp toJson(DateTime date) => Timestamp.fromDate(date);
}
