// This file is "main.dart"
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'Deck.freezed.dart';
part 'Deck.g.dart';

@freezed
class Deck with _$Deck {
  const factory Deck({
    required String id,
    required String user_id,
    required String name,
    required DateTime createDate,
    required bool isShared,
    required String category,
    required String flashcard,
  }) = _Deck;

  factory Deck.fromJson(Map<String, Object?> json) => _$DeckFromJson(json);
}
